# Generated by Django 4.2.5 on 2023-09-27 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuadro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('autor', models.CharField(default='Andrés Honorato', max_length=200)),
                ('coleccion', models.CharField(max_length=200)),
                ('tecnica', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('colores', models.CharField(blank=True, max_length=200)),
                ('cantidad_inicial', models.PositiveIntegerField(blank=True)),
                ('cantidad_restante', models.PositiveIntegerField(blank=True)),
                ('dimension1', models.CharField(blank=True, max_length=100)),
                ('dimension2', models.CharField(blank=True, max_length=100)),
                ('dimension3', models.CharField(blank=True, max_length=100)),
                ('marco1', models.PositiveIntegerField(blank=True)),
                ('marco2', models.PositiveIntegerField(blank=True)),
                ('marco3', models.PositiveIntegerField(blank=True)),
                ('precio1', models.PositiveIntegerField(blank=True)),
                ('precio2', models.PositiveIntegerField(blank=True)),
                ('precio3', models.PositiveIntegerField(blank=True)),
                ('descuento', models.PositiveIntegerField(blank=True)),
                ('envio1', models.PositiveIntegerField(blank=True)),
                ('envio2', models.PositiveIntegerField(blank=True)),
                ('envio3', models.PositiveIntegerField(blank=True)),
                ('imagen1', models.ImageField(blank=True, upload_to='cuadros', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('imagen2', models.ImageField(blank=True, upload_to='cuadros', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('imagen3', models.ImageField(blank=True, upload_to='cuadros', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('imagen4', models.ImageField(blank=True, upload_to='cuadros', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actulizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
