# Generated by Django 4.2.5 on 2023-09-27 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cuadro',
            new_name='Cuadros',
        ),
    ]
