# Generated by Django 4.2.5 on 2023-09-27 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_cuadro_cuadros'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cuadros',
            new_name='Cuadro',
        ),
    ]
