# Generated by Django 4.2.5 on 2023-09-27 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_cuadro_cantidad_inicial_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuadro',
            old_name='cantidad_restante',
            new_name='cantidad_vendidos',
        ),
    ]
