# Generated by Django 4.2.5 on 2023-09-27 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_cantidad_restante_cuadro_cantidad_vendidos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuadro',
            old_name='cantidad_vendidos',
            new_name='cantidad_vendida',
        ),
    ]
