# Generated by Django 4.2.5 on 2023-09-27 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_cantidad_vendidos_cuadro_cantidad_vendida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadro',
            name='imagen1',
            field=models.ImageField(upload_to='cuadros', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
    ]
