# Generated by Django 4.2.5 on 2023-10-01 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_coleccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuadro',
            old_name='coleccion',
            new_name='coleccion4',
        ),
    ]
