# Generated by Django 4.2.5 on 2023-10-02 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_cuadro_coleccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuadro',
            old_name='tecnica',
            new_name='tecnica4',
        ),
    ]
