# Generated by Django 4.2.5 on 2023-10-02 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_tecnica_cuadro_tecnica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadro',
            name='coleccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coleccionX', to='home.coleccion'),
        ),
    ]
