# Generated by Django 4.2.5 on 2023-10-02 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_cuadro_coleccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadro',
            name='tecnica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tecnicaX', to='home.tecnica'),
        ),
    ]
