# Generated by Django 4.2.5 on 2024-05-14 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_cuadro_marco1_remove_cuadro_marco2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuadro',
            old_name='dimension1',
            new_name='marco_con',
        ),
        migrations.RenameField(
            model_name='cuadro',
            old_name='dimension2',
            new_name='marco_sin',
        ),
        migrations.RenameField(
            model_name='cuadro',
            old_name='precio2',
            new_name='precio_con',
        ),
        migrations.RenameField(
            model_name='cuadro',
            old_name='precio1',
            new_name='precio_sin',
        ),
        migrations.RemoveField(
            model_name='cuadro',
            name='dimension3',
        ),
        migrations.RemoveField(
            model_name='cuadro',
            name='envio3',
        ),
        migrations.RemoveField(
            model_name='cuadro',
            name='precio3',
        ),
    ]
