# Generated by Django 4.2.5 on 2024-05-14 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_dimension1_cuadro_marco_con_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuadro',
            name='precio_con',
        ),
        migrations.RemoveField(
            model_name='cuadro',
            name='precio_sin',
        ),
    ]
