# Generated by Django 4.2.5 on 2024-05-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_cuadro_precio_con_remove_cuadro_precio_sin'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadro',
            name='precio_con',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cuadro',
            name='precio_sin',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
