# Generated by Django 4.2.5 on 2024-05-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_cuadro_precio_con_cuadro_precio_sin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadro',
            name='precio_con',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuadro',
            name='precio_sin',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
