# Generated by Django 4.2.5 on 2024-05-14 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_cuadro_precio_con_alter_cuadro_precio_sin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuadro',
            name='marco_con',
        ),
        migrations.RemoveField(
            model_name='cuadro',
            name='marco_sin',
        ),
    ]
