# Generated by Django 4.2.5 on 2024-05-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_cuadro_marco_con_remove_cuadro_marco_sin'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadro',
            name='marco_con',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cuadro',
            name='marco_sin',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
