# Generated by Django 4.2.5 on 2024-05-16 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_cuadro_imagen5_cuadro_imagen6'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadro',
            name='imagen7',
            field=models.ImageField(blank=True, upload_to='cuadros', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='cuadro',
            name='imagen8',
            field=models.ImageField(blank=True, upload_to='cuadros', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='cuadro',
            name='imagen9',
            field=models.ImageField(blank=True, upload_to='cuadros', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
    ]
