# Generated by Django 4.2.5 on 2024-05-25 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_cuadro_imagen1'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadro',
            name='orden',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
