# Generated by Django 4.2.5 on 2024-05-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_cuadro_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadro',
            name='vendido',
            field=models.BooleanField(default=False),
        ),
    ]
