# Generated by Django 4.2.5 on 2024-06-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_cuadro_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadro',
            name='descuento',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
