# Generated by Django 4.2.5 on 2024-06-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_cuadro_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadro',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
