# Generated by Django 4.2.5 on 2024-12-04 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_cuadro_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadro',
            name='marco1',
            field=models.ImageField(blank=True, upload_to='cuadros', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='cuadro',
            name='marco2',
            field=models.ImageField(blank=True, upload_to='cuadros', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='cuadro',
            name='marco3',
            field=models.ImageField(blank=True, upload_to='cuadros', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='cuadro',
            name='marco4',
            field=models.ImageField(blank=True, upload_to='cuadros', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='cuadro',
            name='marco5',
            field=models.ImageField(blank=True, upload_to='cuadros', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
    ]
