# Generated by Django 4.2.5 on 2025-11-25 00:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_remove_cuadro_marco1_remove_cuadro_marco2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerDoble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de referencia para el administrador', max_length=200)),
                ('imagen', models.ImageField(upload_to='banners', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cuadro_1', models.ForeignKey(blank=True, help_text='Selecciona el primer cuadro a vincular', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners_como_1', to='home.cuadro')),
                ('cuadro_2', models.ForeignKey(blank=True, help_text='Selecciona el segundo cuadro a vincular', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners_como_2', to='home.cuadro')),
            ],
        ),
    ]
