# Generated by Django 4.2.5 on 2025-11-25 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_bannerdoble'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerdoble',
            name='coleccion',
            field=models.ForeignKey(blank=True, help_text='Colección a la que pertenece este banner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='home.coleccion'),
        ),
    ]
