# Generated by Django 4.2.5 on 2024-06-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadopago', '0004_alter_mer_cuadro_cantidad_inicial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mer_cuadro',
            name='cantidad_vendida',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
