# Generated by Django 4.2.5 on 2024-06-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadopago', '0005_alter_mer_cuadro_cantidad_vendida'),
    ]

    operations = [
        migrations.AddField(
            model_name='mer_cuadro',
            name='cantidad_disponible',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
